#!/bin/bash

# Can get from wmctrl -d
S_W=$S_W
S_H=$S_H

# Get info of current active window

win_id=$(xprop -root | sed '/_NET_ACTIVE_WINDOW(WINDOW)/ {s/.*\(0x[a-z0-9]\+\)/\1/;q} ; d')

read win_x win_y <<< "$(xwininfo -id $win_id | sed '/Absolute/ {s/[ :a-z-]//gi;p} ; d' | tr '\n' ' ')"
read win_w win_h <<< "$(xwininfo -id $win_id | sed '/\(Width\|Height\)/ {s/[ :a-z-]//gi;p} ; d' | tr '\n' ' ')"
read b_left a_ b_top b_ <<< "$(xprop -id $win_id | sed '/FRAME.*CARDINAL/ {s/[_=(),a-z]//gi;q} ; d')"

# Remove window decoration
((win_x-=b_left))
((win_y-=b_top))

case "$1" in
	u|up)
		NEW_WIN_X=$win_x
		NEW_WIN_Y=$(($win_y+$S_H))
		;;
	d|down)
		NEW_WIN_X=$win_x
		NEW_WIN_Y=$(($win_y-$S_H))
		;;
	l|left)
		NEW_WIN_X=$(($win_x-$S_W))
		NEW_WIN_Y=$win_y
		;;
	r|right)
		NEW_WIN_X=$(($win_x+$S_W))
		NEW_WIN_Y=$win_y
		;;
	*)
		exit 1
		;;
esac

# Somehow, the window gets taller in Fluxbox after moves, has to supply height instead of -1
wmctrl -i -r $win_id -e "1,$NEW_WIN_X,$NEW_WIN_Y,$win_w,$win_h"
